server:
  port: 9999
  servlet:
    context-path: /demo
spring:
  application:
    name: defang-template
  http:
    encoding:
    charset: UTF-8
    enabled: true
    force: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db01?useSSL=false
    username: root
    password: rshi.cn
    poolPingConnectionsNotUsedFor: 60000
    removeAbandoned: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    validationQuery: SELECT 1 FROM DUAL
    initialSize: 5
    maxWait: 60000
    poolPreparedStatements: false
    filters: stat,wall
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    maxActive: 50
    druid:
      user: admin
      password: admin

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  dubbo:
    server: true
    registry: zookeeper://127.0.0.1:2181
    provider:
      port: 20999